using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MyApp.API.Migrations
{
    /// <inheritdoc />
    public partial class AddCheckinAndEventParticipation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""Checkins""') IS NULL THEN
        CREATE TABLE ""Checkins"" (
            ""CheckinID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""EventID"" integer NOT NULL,
            ""ParticipantID"" integer NOT NULL,
            ""Timestamp"" timestamp with time zone NOT NULL
        );
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""EventCheckinSessions""') IS NULL THEN
        CREATE TABLE ""EventCheckinSessions"" (
            ""SessionID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""EventID"" integer NOT NULL,
            ""SessionType"" text NOT NULL,
            ""Token"" character varying(128),
            ""ExpiresAt"" timestamp with time zone,
            ""StartedAt"" timestamp with time zone NOT NULL,
            ""EndedAt"" timestamp with time zone,
            ""IsActive"" boolean NOT NULL
        );
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""EventParticipants""') IS NULL THEN
        CREATE TABLE ""EventParticipants"" (
            ""EventParticipantID"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""EventID"" integer NOT NULL,
            ""UserID"" text NOT NULL
        );
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_EventParticipants_Events_EventID'
    ) THEN
        ALTER TABLE ""EventParticipants""
        ADD CONSTRAINT ""FK_EventParticipants_Events_EventID""
        FOREIGN KEY (""EventID"") REFERENCES ""Events""(""Id"")
        ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ""IX_EventCheckinSessions_EventID_SessionType_IsActive""
ON ""EventCheckinSessions"" (""EventID"", ""SessionType"", ""IsActive"");
");

            migrationBuilder.Sql(@"
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_EventParticipants_EventID_UserID""
ON ""EventParticipants"" (""EventID"", ""UserID"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"Checkins\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"EventCheckinSessions\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"EventParticipants\";");
        }
    }
}
