using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MyApp.API.Migrations
{
    /// <inheritdoc />
    public partial class ImplmentChatSystemWithID : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create Chat tables with conditional SQL to avoid conflicts with existing tables
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""Chats""') IS NULL THEN
        CREATE TABLE ""Chats"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""TripId"" integer NOT NULL,
            ""Title"" text NOT NULL,
            ""CreatorId"" integer NOT NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL
        );
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""ChatMessages""') IS NULL THEN
        CREATE TABLE ""ChatMessages"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""ChatId"" integer NOT NULL,
            ""SenderId"" integer NOT NULL,
            ""Content"" text NOT NULL,
            ""Timestamp"" timestamp with time zone NOT NULL
        );
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF to_regclass('""ChatParticipants""') IS NULL THEN
        CREATE TABLE ""ChatParticipants"" (
            ""ChatId"" integer NOT NULL,
            ""UserId"" integer NOT NULL,
            ""JoinedAt"" timestamp with time zone NOT NULL,
            PRIMARY KEY (""ChatId"", ""UserId"")
        );
    END IF;
END $$;
");

            // Add foreign key constraints
            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Chats_Trips_TripId') THEN
        ALTER TABLE ""Chats""
        ADD CONSTRAINT ""FK_Chats_Trips_TripId""
        FOREIGN KEY (""TripId"") REFERENCES ""Trips""(""Id"") ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Chats_Users_CreatorId') THEN
        ALTER TABLE ""Chats""
        ADD CONSTRAINT ""FK_Chats_Users_CreatorId""
        FOREIGN KEY (""CreatorId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatMessages_Chats_ChatId') THEN
        ALTER TABLE ""ChatMessages""
        ADD CONSTRAINT ""FK_ChatMessages_Chats_ChatId""
        FOREIGN KEY (""ChatId"") REFERENCES ""Chats""(""Id"") ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatMessages_Users_SenderId') THEN
        ALTER TABLE ""ChatMessages""
        ADD CONSTRAINT ""FK_ChatMessages_Users_SenderId""
        FOREIGN KEY (""SenderId"") REFERENCES ""Users""(""Id"") ON DELETE RESTRICT;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatParticipants_Chats_ChatId') THEN
        ALTER TABLE ""ChatParticipants""
        ADD CONSTRAINT ""FK_ChatParticipants_Chats_ChatId""
        FOREIGN KEY (""ChatId"") REFERENCES ""Chats""(""Id"") ON DELETE CASCADE;
    END IF;
END $$;
");

            migrationBuilder.Sql(@"
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_ChatParticipants_Users_UserId') THEN
        ALTER TABLE ""ChatParticipants""
        ADD CONSTRAINT ""FK_ChatParticipants_Users_UserId""
        FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE;
    END IF;
END $$;
");

            // Create indexes if they don't exist
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Chats_TripId"" ON ""Chats""(""TripId"")");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Chats_CreatorId"" ON ""Chats""(""CreatorId"")");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ChatMessages_ChatId"" ON ""ChatMessages""(""ChatId"")");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ChatMessages_SenderId"" ON ""ChatMessages""(""SenderId"")");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ChatParticipants_UserId"" ON ""ChatParticipants""(""UserId"")");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ChatMessages""");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ChatParticipants""");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Chats""");
        }
    }
}
